In [2]:
import torch
import numpy as np

# 텐서 초기화
1. 데이터로 부터 직접 생성하기
2. numpy 배열로부터 생성하기

In [46]:
# 데이터로 부터 직접 생성하기
# 데이터 자료형은 자동으로 유추한다
data = [[1,2], [3,4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [47]:
# NumPy 배열로부터 tensor 생성하기
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [48]:
# 명시적으로 재정의(override)하지 않으면, 인자로 주어진 텐서의 속성(모양(shape), 자료형(datatype))를 유지
x_ones = torch.ones_like(x_data) # x_data 속성 유지
print(f"Ones 텐서: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype = torch.float) # x_data의 속성을 덮어씁니다.
print(f"random tensor: \n {x_rand} \n")

Ones 텐서: 
 tensor([[1, 1],
        [1, 1]]) 

random tensor: 
 tensor([[0.2964, 0.1905],
        [0.3324, 0.5172]]) 



### 무작위(random) 또는 상수(constant) 값을 사용하기

* shape은 텐서의 차원(dimension)을 나타내는 튜플로, 아래 함수들에서는 출력 텐서의 차원을 결정

In [49]:
shape = (2,3,) 
rand_tensor = torch.rand(shape)
one_tensor = torch.ones(shape)
zero_tensor = torch.zeros(shape)

print(f"rand tensor: \n {rand_tensor} \n")
print(f"one tensor: \n {one_tensor} \n")
print(f"zero tensor: \n {zero_tensor} \n")


rand tensor: 
 tensor([[0.9777, 0.0995, 0.1882],
        [0.5400, 0.4690, 0.8892]]) 

one tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

zero tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



# 텐서의 속성
* 텐서의 모양 (shape)
* 텐서의 자료형(datatype)

In [50]:
tensor = torch.rand(3,4)

print(f"shape: \n {tensor.shape} \n")
print(f"datatype: \n {tensor.dtype} \n")
print(f"device tensor is stored on: \n {tensor.device} \n")



shape: 
 torch.Size([3, 4]) 

datatype: 
 torch.float32 

device tensor is stored on: 
 cpu 



# 텐서의 연산
기본적으로 텐서는 cpu에 할당 됨.

In [53]:
#numpy 식의 표준 인덱싱과 슬라이싱

# tensor = torch.ones(3,4)

print(f"tensor: \n {tensor} \n")
print(f"First row: {tensor[0]}")
print(f"fisrt col: {tensor[:,0]}")
print(f"last col: {tensor[..., -1]}")


tensor: 
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) 

First row: tensor([1., 1., 1., 1.])
fisrt col: tensor([1., 1., 1.])
last col: tensor([1., 1., 1.])


In [54]:
tensor[:,3] = 4

* pytorch에서는 텐서는 차원 0부터 센타

dim = 0은 첫번째 차원 (행 방향, batch 차원)
dim = 1은 두번째 차원 (열 방향, feature 차원)

In [55]:
t1 = torch.cat([tensor, tensor, tensor], dim = 1)
t2 = torch.cat([tensor, tensor, tensor], dim =0)
print(t1)
print(t2)

tensor([[1., 1., 1., 4., 1., 1., 1., 4., 1., 1., 1., 4.],
        [1., 1., 1., 4., 1., 1., 1., 4., 1., 1., 1., 4.],
        [1., 1., 1., 4., 1., 1., 1., 4., 1., 1., 1., 4.]])
tensor([[1., 1., 1., 4.],
        [1., 1., 1., 4.],
        [1., 1., 1., 4.],
        [1., 1., 1., 4.],
        [1., 1., 1., 4.],
        [1., 1., 1., 4.],
        [1., 1., 1., 4.],
        [1., 1., 1., 4.],
        [1., 1., 1., 4.]])


## tensor의 산술 연산

In [56]:
print(tensor) # 3 x 4

print(tensor)

tensor([[1., 1., 1., 4.],
        [1., 1., 1., 4.],
        [1., 1., 1., 4.]])
tensor([[1., 1., 1., 4.],
        [1., 1., 1., 4.],
        [1., 1., 1., 4.]])


In [57]:
# 두 텐서 간의 행렬 곱을 계산
# y1 = y2 = y3

y1 = tensor @ tensor.T
print(y1)

y2 = tensor.matmul(tensor.T)
print(y2)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out = y3)
print(y3)



tensor([[19., 19., 19.],
        [19., 19., 19.],
        [19., 19., 19.]])
tensor([[19., 19., 19.],
        [19., 19., 19.],
        [19., 19., 19.]])
tensor([[19., 19., 19.],
        [19., 19., 19.],
        [19., 19., 19.]])


In [58]:
# 요소별 곱
z1 = tensor * tensor
print(z1)

z2 = tensor.mul(tensor)
print(z2)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[ 1.,  1.,  1., 16.],
        [ 1.,  1.,  1., 16.],
        [ 1.,  1.,  1., 16.]])
tensor([[ 1.,  1.,  1., 16.],
        [ 1.,  1.,  1., 16.],
        [ 1.,  1.,  1., 16.]])


tensor([[ 1.,  1.,  1., 16.],
        [ 1.,  1.,  1., 16.],
        [ 1.,  1.,  1., 16.]])

In [59]:
# 단일 요소(single-element) 텐서
# tensor의 모든 값을 sum하여(이를 집계라 하냐? ) 요소가 하나인 텐서의 경우 item()을 사용하여 python 숫자 값으로 dtype 변환


agg = tensor.sum()
print(tensor)
print(agg, type(agg))

agg_item = agg.item()
print(agg_item, type(agg_item))

# 모든 요소에 5 더하기
tensor.add_(5)
print(tensor)

tensor([[1., 1., 1., 4.],
        [1., 1., 1., 4.],
        [1., 1., 1., 4.]])
tensor(21.) <class 'torch.Tensor'>
21.0 <class 'float'>
tensor([[6., 6., 6., 9.],
        [6., 6., 6., 9.],
        [6., 6., 6., 9.]])


# numpy 변환
cpu 상의 텐서와 numpy 배열은 메모리 공간을 공유해서 하나를 변경하면 다른 하나도 변경

그리고 tensor -> numpy 변경 가능, numpy -> tensor 또한 변경 가능

### Tensor -> numpy

In [63]:
t = torch.ones(5)
print(f"t: {t} ")

n = t.numpy()
print(f"n: {n}")

# 기본적으로 torch.ones()는 float32 타입의 센서를 생성
# .이 찍혀나오는 이유는 데이터 타입이 float형이라 그럼

t.add_(3)
print(f"t: {t} ")
print(f"n: {n}")

# int로 바꾸면

t = torch.ones(5, dtype=torch.int)
print(f"t: {t}")

n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.]) 
n: [1. 1. 1. 1. 1.]
t: tensor([4., 4., 4., 4., 4.]) 
n: [4. 4. 4. 4. 4.]
t: tensor([1, 1, 1, 1, 1], dtype=torch.int32)
n: [1 1 1 1 1]


### numpy -> tensor

In [68]:
n = np.ones(5)
t = torch.from_numpy(n)

print(n)
print(t)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [69]:
np.add(n, 2, out=n)
print(n)
print(t)

[3. 3. 3. 3. 3.]
tensor([3., 3., 3., 3., 3.], dtype=torch.float64)
